[web]
version = "1.0.0"
name = "colatiger"
addr = "0.0.0.0:4000"

[milvus]
address = "http://127.0.0.1:19530"

[redis]
dsn = "redis://127.0.0.1:6379/"

[s3]
endpoint = "http://127.0.0.1:9000"
access_key = "minioadmin"
secret_access_key = "minioadmin"
bucket_name = "cola-tiger"
use_ssl= false

[db]
dns = "postgres://root:123456@127.0.0.1:5432/colatiger"
