[web]
version = "1.0.0"
name = "colatiger"
addr = "0.0.0.0:4000"

[milvus]
address = "http://192.168.87.231:19530"

[redis]
dsn = "redis://127.0.0.1:6379/"

[s3]
endpoint = "http://82.156.138.158:9000"
access_key = "minioadmin"
secret_access_key = "minioadmin"
bucket_name = "poc"
use_ssl= false

[db]
dns = "postgres://postgres:your-super-secret-and-long-postgres-password@82.156.138.158:5432/poc"

